version: '3'

networks:
  network-pokedex:

services:
  nginx:
    image: nginx:1.18.0-alpine
    container_name: nginx-pokedex
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - php
    networks:
      - network-pokedex
  php:
    build: docker/php-fpm
    container_name: pokedex
    entrypoint: /entrypoint.sh
    environment:
      CONTAINER_NAME: PHP
      PHP_IDE_CONFIG: ”serverName=xdebug-docker”
      COMPOSER_AUTH: "${COMPOSER_AUTH}"
    #user: "1000:1000"
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"
    networks:
      - network-pokedex
