name: Pokedex-PHP Workflow
on: [push]

jobs:
  build:
    name: Pokedex Laravel Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/composer
      - uses: ./.github/actions/config-laravel
      - run: ./vendor/bin/phpunit
