  name: NPM Workflow
  on:
    push:
      paths:
        - 'resources/js/*'
        -
  jobs:
    build:
      name: Pokedex Laravel Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
